version: '2'
services:
  mongodb:
    build: ./mongodb
    environment:
      - MONGO_DATA_DIR=/data/db
    volumes:
      - ./data/db:/data/db
  server:
    build: ./server
    depends_on:
      - mongodb
    environment:
      - PDS_DEBUG=${PDS_DEBUG}
    ports:
      - 8000:8000
    privileged: true
    volumes:
      - ./server:/plagiarism_detection/server
