version: '2'
services:
  mongodb:
    build: ./mongodb
    hostname: mongodb
    ports:
      - 27017:27107
    volumes:
      - ./data/db:/data/db
  postprocessor:
    build: ./postprocessor
    depends_on:
      - mongodb
    environment:
      - PDP_DEBUG=${PDP_DEBUG}
  server:
    build: ./server
    depends_on:
      - mongodb
    environment:
      - PDP_DEBUG=${PDP_DEBUG}
    ports:
      - 8000:8000
    volumes:
      - ./server:/plagiarism_detection/server
